apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c9e8d5mjj-java-quarkus
  janus-idp.io/tekton: c9e8d5mjj-java-quarkus
  backstage.io/kubernetes-id: c9e8d5mjj-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c9e8d5mjj-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
