apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: c9e8d5mjj-java-quarkus-gitops-repository
spec:
  url: https://github.com/chetna14manku-org/c9e8d5mjj-java-quarkus-gitops